#!/bin/bash
# Author: Enrico Corsaro - May 2014
# e-mail: emncorsaro@gmail.com
# usage ./multirun <KIC_ID> <starting_process_number> <Nprocesses>
# Generates folders and starts computation for each folder, saving the results inside the folder

# make -j 4
echo "Start processes from #$2, for a total of $3 processes"
dir="/YOUR_LOCAL_PATH_HERE/Background/results/"

for ((i=$2; i<($2+$3); i++))
do
    if [ $i -le 9 ]; then
        mkdir "$dir"KIC$1/0$i
        ./background $1 0$i &
    else
        mkdir "$dir"KIC$1/$i
        ./background $1 $i &
    fi
done
